<div class="inner">
    <h3 class="h3">Color Converter</h3>
    <label for"hex">hex: #</label>
    <input id="hex" name="hex" type="number" placeholder="Hex code"/>
    <button data-name="color.hex">HEX me</button>
    <br/>
    <label for"rgb">rgb:</label>
    <input id="rgb_r" name="rgb_r" type="number" placeholder="Red code"/>
    <input id="rgb_g" name="rgb_g" type="number" placeholder="Green code"/>
    <input id="rgb_b" name="rgb_b" type="number" placeholder="Blue code"/>
    <button data-name="color.rgb">RGB me</button>
    <div class="colorconvert_result result empty"></div>
</div>